# Generated by Django 6.0.6 on 2026-06-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pot_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='pot_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
