# Generated by Django 6.0.6 on 2026-06-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_potavatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='potavatar',
            name='item',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
